// Curated showcase set for the home carousel. Base stats are the real Gen-1
// values from PokeAPI, embedded statically so the home page needs no API calls
// and the holo cards render correct HP/ATK/DEF/SPD immediately.
export const FEATURED_POKEMON = [
  {
    id: 1,
    name: 'bulbasaur',
    type: 'grass',
    stats: { hp: 45, attack: 49, defense: 49, specialAttack: 65, specialDefense: 65, speed: 45 },
  },
  {
    id: 4,
    name: 'charmander',
    type: 'fire',
    stats: { hp: 39, attack: 52, defense: 43, specialAttack: 60, specialDefense: 50, speed: 65 },
  },
  {
    id: 7,
    name: 'squirtle',
    type: 'water',
    stats: { hp: 44, attack: 48, defense: 65, specialAttack: 50, specialDefense: 64, speed: 43 },
  },
  {
    id: 25,
    name: 'pikachu',
    type: 'electric',
    stats: { hp: 35, attack: 55, defense: 40, specialAttack: 50, specialDefense: 50, speed: 90 },
  },
  {
    id: 6,
    name: 'charizard',
    type: 'fire',
    stats: { hp: 78, attack: 84, defense: 78, specialAttack: 109, specialDefense: 85, speed: 100 },
  },
  {
    id: 9,
    name: 'blastoise',
    type: 'water',
    stats: { hp: 79, attack: 83, defense: 100, specialAttack: 85, specialDefense: 105, speed: 78 },
  },
  {
    id: 3,
    name: 'venusaur',
    type: 'grass',
    stats: { hp: 80, attack: 82, defense: 83, specialAttack: 100, specialDefense: 100, speed: 80 },
  },
  {
    id: 39,
    name: 'jigglypuff',
    type: 'fairy',
    stats: { hp: 115, attack: 45, defense: 20, specialAttack: 45, specialDefense: 25, speed: 20 },
  },
  {
    id: 54,
    name: 'psyduck',
    type: 'water',
    stats: { hp: 50, attack: 52, defense: 48, specialAttack: 65, specialDefense: 50, speed: 55 },
  },
  {
    id: 63,
    name: 'abra',
    type: 'psychic',
    stats: { hp: 25, attack: 20, defense: 15, specialAttack: 105, specialDefense: 55, speed: 90 },
  },
  {
    id: 74,
    name: 'geodude',
    type: 'rock',
    stats: { hp: 40, attack: 80, defense: 100, specialAttack: 30, specialDefense: 30, speed: 20 },
  },
  {
    id: 92,
    name: 'gastly',
    type: 'ghost',
    stats: { hp: 30, attack: 35, defense: 30, specialAttack: 100, specialDefense: 35, speed: 80 },
  },
  {
    id: 94,
    name: 'gengar',
    type: 'ghost',
    stats: { hp: 60, attack: 65, defense: 60, specialAttack: 130, specialDefense: 75, speed: 110 },
  },
  {
    id: 113,
    name: 'chansey',
    type: 'normal',
    stats: { hp: 250, attack: 5, defense: 5, specialAttack: 35, specialDefense: 105, speed: 50 },
  },
  {
    id: 131,
    name: 'lapras',
    type: 'ice',
    stats: { hp: 130, attack: 85, defense: 80, specialAttack: 85, specialDefense: 95, speed: 60 },
  },
  {
    id: 133,
    name: 'eevee',
    type: 'normal',
    stats: { hp: 55, attack: 55, defense: 50, specialAttack: 45, specialDefense: 65, speed: 55 },
  },
  {
    id: 143,
    name: 'snorlax',
    type: 'normal',
    stats: { hp: 160, attack: 110, defense: 65, specialAttack: 65, specialDefense: 110, speed: 30 },
  },
  {
    id: 149,
    name: 'dragonite',
    type: 'dragon',
    stats: { hp: 91, attack: 134, defense: 95, specialAttack: 100, specialDefense: 100, speed: 80 },
  },
  {
    id: 150,
    name: 'mewtwo',
    type: 'psychic',
    stats: {
      hp: 106,
      attack: 110,
      defense: 90,
      specialAttack: 154,
      specialDefense: 90,
      speed: 130,
    },
  },
  {
    id: 151,
    name: 'mew',
    type: 'psychic',
    stats: {
      hp: 100,
      attack: 100,
      defense: 100,
      specialAttack: 100,
      specialDefense: 100,
      speed: 100,
    },
  },
  {
    id: 130,
    name: 'gyarados',
    type: 'water',
    stats: { hp: 95, attack: 125, defense: 79, specialAttack: 60, specialDefense: 100, speed: 81 },
  },
  {
    id: 59,
    name: 'arcanine',
    type: 'fire',
    stats: { hp: 90, attack: 110, defense: 80, specialAttack: 100, specialDefense: 80, speed: 95 },
  },
  {
    id: 65,
    name: 'alakazam',
    type: 'psychic',
    stats: { hp: 55, attack: 50, defense: 45, specialAttack: 135, specialDefense: 95, speed: 120 },
  },
  {
    id: 68,
    name: 'machamp',
    type: 'fighting',
    stats: { hp: 90, attack: 130, defense: 80, specialAttack: 65, specialDefense: 85, speed: 55 },
  },
  {
    id: 38,
    name: 'ninetales',
    type: 'fire',
    stats: { hp: 73, attack: 76, defense: 75, specialAttack: 81, specialDefense: 100, speed: 100 },
  },
  {
    id: 103,
    name: 'exeggutor',
    type: 'grass',
    stats: { hp: 95, attack: 95, defense: 85, specialAttack: 125, specialDefense: 75, speed: 55 },
  },
  {
    id: 115,
    name: 'kangaskhan',
    type: 'normal',
    stats: { hp: 105, attack: 95, defense: 80, specialAttack: 40, specialDefense: 80, speed: 90 },
  },
  {
    id: 144,
    name: 'articuno',
    type: 'ice',
    stats: { hp: 90, attack: 85, defense: 100, specialAttack: 95, specialDefense: 125, speed: 85 },
  },
  {
    id: 145,
    name: 'zapdos',
    type: 'electric',
    stats: { hp: 90, attack: 90, defense: 85, specialAttack: 125, specialDefense: 90, speed: 100 },
  },
  {
    id: 146,
    name: 'moltres',
    type: 'fire',
    stats: { hp: 90, attack: 100, defense: 90, specialAttack: 125, specialDefense: 85, speed: 90 },
  },
] as const;

export type FeaturedPokemon = (typeof FEATURED_POKEMON)[number];
